### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by o4410o** [o4410o/furima-29253#9]
フリマアプリのURL
https://furima-29253.herokuapp.com/

出品者用
メールアドレス：aa@aa
パスワード：aaa111

購入者用
メールアドレス：bb@bb
パスワード：aaa111

カード情報
番号：4242424242424242
期限：5/25
cvc：123

**Comment by mutorisa** [comment]
大川さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○IssueにBasic認証の「ユーザー名及びパスワード」を記載しましょう。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by o4410o** [comment]
Basic認証
ユーザー名：admin
パスワード：2222

**Comment by mutorisa** [comment]
大川さん、再度ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○Issueに記載してある「購入者用」及び「出品用」のメールアドレスとパスワードでログインすることができない状態です。正常にログインできるようにしましょう**

**※ログイン後の挙動確認はできていない為、次回提出時に併せて確認させていただきます。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by o4410o** [comment]
修正しました。

**Comment by o4410o** [comment]
フリマアプリのURL
https://furima-29253.herokuapp.com/

出品者用
メールアドレス：aa@aa
パスワード：aaa111

購入者用
メールアドレス：bb@bb
パスワード：aaa111

カード情報
番号：4242424242424242
期限：5/25
cvc：123

**Comment by mutorisa** [comment]
大川さん、再度ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
